### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by stantonhive** [Etayson/fraction-kangaroo#1]
tell me, having an array of RAM, can I solve puzzles 125-130 with this program?

**Comment by devison92** [comment]
Is there any way to contact you via telegram?

**Comment by stantonhive** [comment]
Etar, tell me please, what recommended parameters can I use for 8 cards 3070? what is the correct way to use the -dbit option? can't I point 42 at will to the range 125? And is it normal if I use -DP 32 for such an amount?

**Comment by Etayson** [comment]
This program used JLP kangaroo so you need to have JLP kangaroo in the same folder.
-dbit it is number of divisor
-dbit 2 mean 2^2=4, -dbit 6 mean 2^6=64
For ex. you want devide puzzle #125(124 bit) by 64 so -dbit 6
After that you will have 64 public keys and searching range will be 2^124/2^6=2^118
Only one of this 64 public keys will lie in range 2^118
Else you can start not only from zero position but from any in range 0 to number of divisor-1 = 0..63 (0..3F in HEX) to do use -pos, for ex, -pos F mean start from position 15
About DP, you need to set DP size depending on what search range you will have after division.
Try it on a small range first to see how it works.
If you are a very-very lucky you can try this program.
But if luck is not on your side, then you will spend much-much-much more time than using a regular kangaroo.
**So i recommend using regular kangaroo.**

**Comment by stantonhive** [comment]
> This program used JLP kangaroo so you need to have JLP kangaroo in the same folder. -dbit it is number of divisor -dbit 2 mean 2^2=4, -dbit 6 mean 2^6=64 For ex. you want devide puzzle #125(124 bit) by 64 so -dbit 6 After that you will have 64 public keys and searching range will be 2^124/2^6=2^118 Only one of this 64 public keys will lie in range 2^118 Else you can start not only from zero position but from any in range 0 to number of divisor-1 = 0..63 (0..3F in HEX) to do use -pos, for ex, -pos F mean start from position 15 About DP, you need to set DP size depending on what search range you will have after division. Try it on a small range first to see how it works. If you are a very-very lucky you can try this program. But if luck is not on your side, then you will spend much-much-much more time than using a regular kangaroo. **So i recommend using regular kangaroo.**

Thanks Etar.
